### ISSUE TITLE
duplicate rows in get_interactions_by_taxa results

### ISSUE THREAD

**Issue by jhpoelen** [ropensci/rglobi#13]
as reported by @jemmybutton:

Something goes wrong with "interactions subsetted by adding additional information" test, but it seems to be something on the server side, because request that seems normal http://api.globalbioticinteractions.org:80/interaction?&sourceTaxon=Rattus%20rattus&targetTaxon=Buteo%20platypterus&bbox=&includeObservations=f&type=csv returns duplicated rows (three identical entries for Rattus rattus INTERACTS_WITH Buteo platypterus) and, as a result, data.frames in test do not merge as expected.

**Comment by jhpoelen** [comment]
@jemmybutton duplicates should no longer occur. Please re-open issue if you feel the issue has not been resolved. 

Please note that for symmetric interaction types (e.g. interactsWith or symbiontOf), duplicates may _seem_ to appear if "inverse" observations are made. For instance, ```man interacts with dog``` was recorded and ```dog interacts with man```. Now, when retrieving all dog interactions, two records will be present: ```dog interacts with man``` and ```dog inverseOf(interacts with) man```. The latter resolves to ```dog interacts with man``` thus leading to a seemly duplicate observation.

Curious to hear you thoughts on this.

**Comment by jemmybutton** [comment]
Great! Seems to pass the test (new version) now (on my computer, i don't know how to rerun it on server).
I think, since one of obvious use scenarios for this data is graph construction, there should be some separation of symmetric and asymmetric interaction types. While two opposing edges between two nodes clearly do carry some information when edges are directed (two species, for example, can eat each other and that information is meaningful), that's not so for undirected ones (or is it? i'm not sure if having two edges for Rattus rattus interacts_with Rattus rattus means something). So, if "undirectedness" is sometimes encoded by two interaction entries, in some hypotetical cases user would need to manually remove these duplicates for symmetric interactions to avoid confusion between genuine bi-directional edges and undirected ones and that's not very elegant.

**Comment by jhpoelen** [comment]
Your comments and observations helped me to improve some of the GloBI API. Previously, the includeObservations parameter didn't really do much for the ```/interaction/``` endpoint: it always returned the observations. Now, I've ensured that the parameter works as it does for the ```/taxon/``` endpoint. In addition, I've added a separate test case to define the (slightly) different merging behavior between distinct interactions and individual interaction observations (see [commit](https://github.com/ropensci/rglobi/commit/f58b3aa7f99727ba7caa7d8d07a570c79bd7fa4d)). 

About these symmetric and asymmetric interactions . . . I think I might be better able to express myself with two attached figures. The first (with ate/eaten by) shows what I referred to as an "asymmetric" interaction (ie inverse <> non-inverse). The second (with interacts with) is what I called a "symmetric" interaction (ie inverse == non-inverse). The interaction graph is modeled bidirectionally in both cases on both specimen (or observation) level and taxon level. 

Does this makes sense? I am open to suggestion on nomenclature or modeling improvements.

![interactionmodelasymmetric](https://cloud.githubusercontent.com/assets/1084872/5640605/5d9d0ab6-95dc-11e4-8341-f5da612b654b.png)
![interactionmodelsymmetric](https://cloud.githubusercontent.com/assets/1084872/5640606/5da8ccc0-95dc-11e4-86a6-2cec78dac340.png)
