### ISSUE TITLE
Test failures with dev version of testthat

### ISSUE THREAD

**Issue by hadley** [ropensci/rglobi#20]
```
checking tests ... ERROR
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  9: query(cypher, opts = opts)
  10: rjson::fromJSON(h$value())
  11: stop(x)
  
  testthat results ================================================================
  OK: 20 SKIPPED: 0 FAILED: 4
  1. Error: cypher query 
  2. Error: no result cypher query 
  3. Error: interaction matrix can be retrieved 
  4. Error: interaction matrix with interaction type can be retrieved 
  
  Error: testthat unit tests failed
  Execution halted
```

Can you please take a look?

**Comment by jhpoelen** [comment]
@hadley thanks for your message - I reproduced and fixed the issue. The root cause was a third party taxonomic name integration that, for some reason, no longer returned full taxonomic names. I fixed it by reverting to a previous version of the species interaction dataset. No changes to the R code were made.

**Comment by jhpoelen** [comment]
PS @hadley what do you use to trigger scheduled build on travis?

**Comment by hadley** [comment]
I don't trigger scheduled builds - this is all "by hand" :/
