### ISSUE TITLE
Search by standardized taxonomic identifier

### ISSUE THREAD

**Issue by jebyrnes** [ropensci/rglobi#42]
I'm running into an issue where I have interactions I'm interested in for species that have undergone taxonomic revision. However, rglobi uses the given taxonomy instead of a standard identifier.  Would it be possible to use WORMS or some other id to search instead of a taxon name? Or even make this transparent on the backend

e.g.

```
a <- get_interactions("Laminaria saccharina", interaction.type = c("eats", "eatenBy", "preysOn", "preyedUponBy") )

b <- get_interactions("Saccharina latissima", interaction.type = c("eats", "eatenBy", "preysOn", "preyedUponBy") )
```

should produce the same data frame. They do not. `a` is 108 rows and `b` is 126 rows. This can present a big problem - and likely a larger one in terms of creating incomplete interaction webs.

**Comment by jhpoelen** [comment]
@jebyrnes you should be able to search by WORMS identifiers. 

In your comments, I see a couple of separate issues:

1. a question search by taxonomic identifiers
2. suspicious results in which results for related names (e.g., "Laminaria saccharina" and "Saccharina latissima") are expected to be identical but are not.

**Comment by jebyrnes** [comment]
Great! And, yes, these are the two salient issues!

**Comment by jhpoelen** [comment]
the GloBI API and rglobi supports searching by taxon id. 

For WORMS, you'd have to add WORMS:[some aphia] number. 

For _Saccharina latissima_ the combo of this prefix and aphia number appears to be: WORMS:234483 .
Also, as far as I can tell, on GloBI, _Laminaria saccharina_ also points to the WORMS:234483 .

**Comment by jhpoelen** [comment]
I was able to reproduce your earlier observation:

```R
> install.packages('rglobi')
...
> a <- rglobi::get_interactions("Laminaria saccharina", interaction.type = c("eats", "eatenBy", "preysOn", "preyedUponBy") )
> b <- rglobi::get_interactions("Saccharina latissima", interaction.type = c("eats", "eatenBy", "preysOn", "preyedUponBy") )
> dim(a)                                                                      
[1] 108  13
> dim(b)
[1] 126  13
```

**Comment by jhpoelen** [comment]
Confusingly searching by just the WORMS:234483 yield fewer results :

```R
c <- rglobi::get_interactions("WORMS:234483", interaction.type = c("eats", "eatenBy", "preysOn", "preyedUponBy") )
> dim(c)
[1] 76 13
```

The root cause for this can originate in from many sources, and the taxonomic assumptions are crystallized in the GloBI taxon name graph.

From https://globalbioticinteractions.org/process page -

```
[5] Name link table, or GloBI Taxon Graph, is the (published) outcome of the Taxon Graph Builder. The link table associated verbatim names to known taxon name concepts. See published versions at doi:10.5281/zenodo.755513 .
``` 

Taking the most recent taxon graph, you'll find:

Poelen, Jorrit H. (2021). Global Biotic Interactions: Taxon Graph (0.3.34) [Data set]. Zenodo. https://doi.org/10.5281/zenodo.5526782

with 

https://zenodo.org/record/5526782/files/taxonMap.tsv.gz (the translation table provided -> resolved)

and 

https://zenodo.org/record/5526782/files/taxonCache.tsv.gz (the full name list)

**Comment by jhpoelen** [comment]
For your convenience, I've attached a zip file with the (likely incorrect) taxonomic interpretation of the relevant names, as reported in the taxon name graph.  But hey, at least, we know exactly what was translated into what.

```
$ cat README 
Files generated on 2021-11-16 using: 

 2056  curl -L "https://zenodo.org/record/5526782/files/taxonMap.tsv.gz" | gunzip | grep "Laminaria saccharina" > Laminaria_saccharina_map.tsv
 2057  curl -L "https://zenodo.org/record/5526782/files/taxonCache.tsv.gz" | gunzip | grep "Laminaria saccharina" > Laminaria_saccharina_cache.tsv
 2058  curl -L "https://zenodo.org/record/5526782/files/taxonCache.tsv.gz" | gunzip | grep "Saccharina latissima" > Saccharina_latissima_cache.tsv
 2059  curl -L "https://zenodo.org/record/5526782/files/taxonMap.tsv.gz" | gunzip | grep "Saccharina latissima" > Saccharina_latissima_map.tsv
 2060  curl -L "https://zenodo.org/record/5526782/files/taxonMap.tsv.gz" | gunzip | grep "WORMS:234483" > WORMS_234483_map.tsv
 2061  curl -L "https://zenodo.org/record/5526782/files/taxonCache.tsv.gz" | gunzip | grep "WORMS:234483" > WORMS_234483_cache.tsv
```

[byrnes_42.zip](https://github.com/ropensci/rglobi/files/7550942/byrnes_42.zip)

**Comment by jhpoelen** [comment]
As you can see, it appears that

```
	(Laminaria saccharina) -> (WORMS:234483 | Saccharina latissima)
```

but also 

```
	(Ulva latissima) ->	( IRMNG:10009757 | Laminaria saccharina)
```

and even more ambiguous:

```
	(Laminaria saccharina) ->( IRMNG:10009757 | Laminaria saccharina)
	(Laminaria saccharina) ->( IRMNG:11178655 | Saccharina latissima
```

**Comment by jhpoelen** [comment]
Also, 

```
	(Ulva latissima) -> (GBIF:4377207 | Saccharina latissima)
```

But no such mapping was found to WORMS . 

Given the many taxonomies that GloBI integrates with, it is unsurprising that some of them produce ambiguous or partly overlapping results. 

@jebyrnes which taxonomic interpretation would you like to follow? Do you have a specific version of WORMS in mind? I'd be happy to figure out a better way to pick a single taxonomic perspective rather than the pluralistic one that GloBI currently uses. 

Note that all the raw, uninterpreted names are still available, to re-interpreting these names should be doable, especially with offline enabled tools like https://github.com/globalbioticinteractions/nomer .

**Comment by jhpoelen** [comment]
@jebyrnes I noticed our discussion around taxonomic interpretation of species interaction data from 2021. Please feel free to comment, or open a new issue if you'd like to share additional ideas on this.

Please also note that @jtmiller28 and @seltmann have helped put together a name alignment workshop that may be of interest to you - see https://big-bee-network.github.io/name-alignment-workshop . 

![image](https://user-images.githubusercontent.com/1084872/230611602-b0151b11-c136-4c57-b8c1-19593093bbb8.png)
